### PR TITLE
Algolia search

### PR DESCRIPTION
**Pull request by pwright**

### CODE REVIEW

**Comment by EricWittmann** [comment]
Is there an example of this in use for another project?  I'd like to see how it looks.

We'll need to adapt the CI process to GitHub actions.  @pwright could you work with @riprasad on updating the GitHub workflow here:  https://github.com/Apicurio/apicurio-docs-playbook/blob/master/.github/workflows/publish.yaml  to add the search indexing?

**Comment by smccarthy-ie** [comment]
@EricWittmann These sites use Algolia for search:

- https://camel.apache.org/docs/ 
- https://docs.antora.org/antora/2.3/

**Comment by pwright** [comment]
@riprasad Hi, i've finally updated this PR... 
The weird thing about the search index is that it's scraped from apicur.io website, not from the 'source' files. Ideally it would happen after each update to the github pages repo. Is that even possible? 
I'd suggest that maybe running manually after each release would be good enough. 

I do need help with the UI. ATM the search box is pretty ugly 

Peek 2021-03-01 19-29

**Comment by EricWittmann** [comment]
The problem with updating/scraping after the github pages content has changed is that the rebuild of the resulting web site is asynchronous.  So it's not clear how long we would need to wait before triggering a rebuild of the index.

**Comment by pwright** [comment]
Apparently, there's an option to scrape every 24hr, investigating...

**Comment by pwright** [comment]
closing in favor of #5

**Pull request closed without merging**
